[pytest]
markers=
    smoke : Smoke test cases
    regression : Regression test cases
    login : Login test cases
    intentory : Inventory test cases
    cart : cart test cases

#addopts = -v --html=reports/report.html --self-contained-html
addopts = -v --html=SWAGLABSTEST/reports/report.html --self-contained-html